### ISSUE TITLE
Create mock data and visualizations of what a heatmap for a specific urban area would look like

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#75]

**Comment by nivashini10** [comment]
Initial thoughts - 

To create the mock data and visualizations, 
1. Understand how current C02 emissions data are being produced
2. The methodology behind the data collection (whether the data are estimates or accurate values of co2 emitted in a location) 

In the Vulcan mapping project, the researchers map the CO2 emissions throughout United States. The data from the Vulcan mapping project is available on the Oak Ridge National Laboratory Data Archive.

Reference: “The Vulcan Version 3.0 High‐Resolution Fossil Fuel CO2 Emissions for the United States” by Kevin R. Gurney, Jianming Liang, Risa Patarasuk, Yang Song, Jianhua Huang and Geoffrey Roest, 15 September 2020, JGR Atmospheres.
[DOI: 10.1029/2020JD032974] (https://doi.org/10.1029/2020JD032974)

**Comment by keenanjohnson** [comment]
That sounds good! In my experience most of those data sets are based on estimates, but I'm not familiar with that one, so I'm excited to see what you find! 

In my opinion, it might end up being simplest to try and handcraft some data that is obviously simpler than a real dataset, but is adequate for these visualizations. Or you could download some data from one of our real sensors and try duplicating it and shifting that data in time to simulate CO2 blowing across an area with wind?

**Comment by nivashini10** [comment]
Using https://towardsdatascience.com/visualizing-climate-change-data-with-python-74ea5bac8756 to create some basic code and visualizations/animations for north America. 

To understand the methodology of the Vulcan Project - Documentation (https://vulcan.rc.nau.edu/assets/files/Vulcan.documentation.v2.0.online.pdf).

![image](https://user-images.githubusercontent.com/70036680/157544788-d22eef9f-470d-4497-9190-fe23ea372ea2.png)

The data is collected from 5 primary sources 
- NEI (National Emissions Inventory) - Emissions data from various data sources
- ETS/CEMs data - supplies CO2 emissions directly and is either directly 
measured CO2 or calculated from fuel consumption measurements and fuel carbon 
content of electricity production sector. 
- Aero2k dataset - supplies the other component of aircraft emissions by quantifying the CO2 emissions. 
- NMIM (National Mobile Inventory Model) - supplies vehicle miles traveled data for each vehicle type, road type, county and month.  combined with fleet information, vehicle emission factors, and a GIS road atlas in order to locate emissions as roadway line sources 
- Portland Cement - Non-fuel combustion cement emissions are derived from individual reported cement facility capacity and state or state-aggregate capacity factors.

The data is in nc4 format. I know how to open nc files using xarray package in python but for some reason, this data doesn't work. Need to do further research on reading this file type.

**Comment by nivashini10** [comment]
Came across https://github.com/claudian37/DS_Portfolio/blob/master/NYC_cab_dataset/01_EDA_NYC_Cab_geospatial_visualization.ipynb  on a Time-Lapsed Heatmap of NYC Cab Pickup Locations. I would be using this as a reference to create the visualizations for the mock-up data and try to mimic some aspects. 

The reason why I am specifically referring to this is because the attributes used in the data are fairly simple (pickup_datetime, pickup_longitude, pickup_latitude) and the mock-up would have almost the same format.

**Comment by keenanjohnson** [comment]
Sounds good! That seems like an excellent place to start. What sort of tools are you using to do that? What stage are you at with the mockups?

**Comment by keenanjohnson** [comment]
For the record I made a smaller gif :) 
![small](https://user-images.githubusercontent.com/2559382/159787522-a9971017-6761-4f94-b069-ef368a9bdc7c.gif)

**Comment by nivashini10** [comment]
I created a github fork and added the codes and datasets under Data Visualizations folder. I was also able to clone the fork to my github desktop. 

I am uploading the heatmap gifs I have created so far and working on adding some markers to show the sensors physical location on the heatmap as well.

**Comment by nivashini10** [comment]
Uploaded some heatmap visualizations [code](https://github.com/nivashini10/ribbit-network-dashboard/blob/78d4763faa22086974ac818fd3c634a40a19bb10/DataVisualizations/CO2%20Visualizations.ipynb), and working on changing the location of the region from Europe to a region in USA and converting it into a gif.

**Comment by keenanjohnson** [comment]
Looking great so far! Are you figuring out git and github ok?

Make sure to include the test data set as well :)

**Comment by nivashini10** [comment]
Created this code https://github.com/Ribbit-Network/ribbit-network-dashboard/blob/main/DataVisualizations/NYC%20CO2%20Visualization.ipynb for visualizing CO2 emissions along with physical sensors shown on the map in NYC. 

I used the NYC Cab dataset to get the coordinates but unable to upload it as the file is too big. The dataset used for the sensors shown on the map is uploaded. 


![pickup_heatmap](https://user-images.githubusercontent.com/70036680/165249792-57be00fd-5ca0-4483-97e4-2bd9a5382726.gif)

**Comment by keenanjohnson** [comment]
I think this is complete!
